{
 "title": "Clickhouse - Data Analysis New",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": "SELECT name FROM system.databases;"
   },
   {
    "name": "table",
    "query": "SELECT name FROM system.tables WHERE database IN (${database})"
   }
  ]
 },
 "panels": [
  {
   "title": "Total rows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  sum(total_rows) as \"Total rows\" FROM system.tables WHERE database IN (${database}) AND name IN (${table})"
    }
   ]
  },
  {
   "title": "Total columns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() as \"Total columns\" FROM system.columns WHERE database IN (${database}) AND table IN (${table})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    name as Name,\n    path as Path,\n    formatReadableSize(free_space) as Free,\n    formatReadableSize(total_space) as Total,\n    1 - free_space/total_space as Used\nFROM system.disks"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select event.event_name, event.commits.timestamp, event.commits.id, event.commits.message, event.commits.author.name, event.repository.name from test.github_json SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select event.event_name, count(*) from test.github_json where event.event_name in ('push','repository_update') group by event.event_name SETTINGS describe_extend_object_types=1;"
    }
   ]
  }
 ]
}