FROM golang:1.19 AS builder
WORKDIR /
COPY ./ ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/client client/main.go

FROM scratch
COPY --from=builder ./build/client client
USER 1101:1101
ENTRYPOINT ["./client"]
