{
 "title": "Clickhouse - Container Bridge",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "database",
    "query": "SELECT name FROM system.databases;"
   },
   {
    "name": "table",
    "query": "SELECT name FROM system.tables WHERE database IN (${database})"
   }
  ]
 },
 "panels": [
  { "title": "Total rows", "type": "stat", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Describe container bridge table",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "Describe bridge.container_bridge SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Container Bridge Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select event.repoName \"Repo Name\", event.event.action Action, event.event.id ID, event.event.target.size Size, event.event.target.repository Name, event.event.target.tag Tag, event.event.target.digest Digest from bridge.container_bridge SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Containers with tag details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select event.repoName \"Repo Name\", event.event.action Action, event.event.id ID, event.event.target.size Size, event.event.target.repository Name, event.event.target.tag Tag, event.event.target.digest Digest from bridge.container_bridge where event.event.target.tag != '' SETTINGS describe_extend_object_types=1;"
    }
   ]
  }
 ]
}